source 'https://rubygems.org'

gem 'json'
gem 'rest-client'
gem 'hashie'

group :test do
  gem 'vcr'
  gem 'rspec-pride'
  gem 'rspec'
  gem 'webmock'
  gem 'simplecov', :require => false
end

gemspec
