source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'jquery-rails'
gem 'wetube', :path => '../wetube-gem'
gem 'hashie'
gem 'rest-client'
gem 'faye'
gem 'thin'
gem 'private_pub'
gem 'pry'
gem 'therubyracer'

group :test do
  gem 'sqlite3'
end

group :development do
  gem 'quiet_assets'
end

group :development, :production do
  gem 'pg'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test do
  gem 'rspec-rails'
  gem 'simplecov'
  gem 'vcr'
  gem 'webrat'
end

